### ISSUE TITLE
composer installation fails with error

### ISSUE THREAD

**Issue by vaughany** [nodes-php/counter-cache#1]
Hi. I tried installing `counter-cache` into Laravel 5.2.32 without success. Command used:

```
$ composer require nodes/counter-cache
```

Result:

```
Installation failed, reverting ./composer.json to its original content.
[ErrorException]                                
dirname() expects exactly 1 parameter, 2 given
```

I know little about how composer works so unfortunately I cannot suggest a solution.

Would it be possible to get some basic information on how to set up and use the plugin?

Cheers.

**Comment by Casperhr** [comment]
Hi, sorry for late reply. what php version are you on?

**Comment by vaughany** [comment]
Hiya. `php -v` gives:

```
PHP 5.6.11-1ubuntu3.4 (cli) 
```

Cheers.

**Comment by Casperhr** [comment]
Ok that should be just fine

I don't get that error.
Try to disable composer scripts from running.

**Comment by rugaard** [comment]
Hey @vaughany

We've just refactored some of our internal packages and we've modified the `composer.json` of this package as well.

So maybe try and install it again. But make sure to use the latest `1.x` release.

Try running this command:
```
composer require nodes/counter-cache:^1.0
